# Generated by Django 4.2.30 on 2026-07-28 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_structure', models.CharField(blank=True, max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='api.departement')),
            ],
            options={
                'verbose_name': 'Structure sanitaire',
                'verbose_name_plural': 'Structures sanitaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur système'), ('coordination', 'Coordination ORHS'), ('analyste', 'Analyste / Statisticien'), ('validateur', 'Validateur'), ('collecteur', 'Collecteur'), ('decideur', 'Décideur'), ('partenaire', 'Partenaire accrédité')], max_length=20)),
                ('scope', models.CharField(choices=[('national', 'National'), ('departemental', 'Départemental'), ('structure', 'Structure')], default='national', max_length=20)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('poste', models.CharField(blank=True, max_length=200)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='api.departement')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='api.structure')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
