# Generated by Django 4.2.30 on 2026-07-28 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('annee', models.PositiveSmallIntegerField()),
                ('periode', models.CharField(blank=True, max_length=40)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campagne de collecte',
                'verbose_name_plural': 'Campagnes de collecte',
                'ordering': ['-annee', '-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='population',
            field=models.PositiveIntegerField(default=0, help_text='Population estimée pour le calcul des ratios RH.'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='type_structure',
            field=models.CharField(choices=[('CHU', 'Centre hospitalier universitaire'), ('HZ', 'Hôpital de zone'), ('CS', 'Centre de santé'), ('CSCOM', 'Centre de santé de commune'), ('CNHU', 'Centre national hospitalier universitaire'), ('PRIVE', 'Établissement privé'), ('DIRECTION', 'Direction départementale')], default='CS', max_length=20),
        ),
        migrations.CreateModel(
            name='ZoneSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones_sanitaires', to='api.departement')),
            ],
            options={
                'verbose_name': 'Zone sanitaire',
                'verbose_name_plural': 'Zones sanitaires',
                'ordering': ['departement__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationRHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide_departement', 'Validé département'), ('valide_national', 'Validé national'), ('rejete', 'Rejeté')], default='brouillon', max_length=25)),
                ('effectif_total', models.PositiveIntegerField(default=0)),
                ('medecins', models.PositiveIntegerField(default=0)),
                ('infirmiers', models.PositiveIntegerField(default=0)),
                ('sages_femmes', models.PositiveIntegerField(default=0)),
                ('dont_femmes', models.PositiveIntegerField(default=0)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_valide_dept', models.DateTimeField(blank=True, null=True)),
                ('date_valide_national', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rejet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='api.campagnecollecte')),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_soumises', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='api.structure')),
                ('valide_dept_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_validees_dept', to=settings.AUTH_USER_MODEL)),
                ('valide_national_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_validees_national', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Déclaration RHS',
                'verbose_name_plural': 'Déclarations RHS',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='structure',
            name='zone_sanitaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='api.zonesanitaire'),
        ),
        migrations.AddConstraint(
            model_name='declarationrhs',
            constraint=models.UniqueConstraint(fields=('campagne', 'structure'), name='unique_declaration_campagne_structure'),
        ),
    ]
