# Generated by Django 4.2.30 on 2026-07-28 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_campagnecollecte_departement_population_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationrhs',
            name='administratifs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='agents_entretien',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='agents_sante_communautaire',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='autre_personnel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='autres_paramedicaux',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='chirurgiens_dentistes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='departs_retraite_12_mois',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='departs_retraite_6_mois',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='dont_hommes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='infirmiers_auxiliaires',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='kinesitherapeutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='medecins_generalistes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='medecins_specialistes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='pharmaciens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='postes_budgetes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='postes_pourvus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='postes_vacants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='sages_femmes_auxiliaires',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='techniciens_imagerie',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='declarationrhs',
            name='techniciens_laboratoire',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ImportFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_cours', max_length=20)),
                ('lignes_total', models.PositiveIntegerField(default=0)),
                ('lignes_ok', models.PositiveIntegerField(default=0)),
                ('lignes_erreur', models.PositiveIntegerField(default=0)),
                ('rapport_erreurs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='api.campagnecollecte')),
                ('importe_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_fichiers', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='api.structure')),
            ],
            options={
                'verbose_name': 'Import fichier',
                'verbose_name_plural': 'Imports fichiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(max_length=120)),
                ('grade', models.CharField(blank=True, max_length=120)),
                ('specialite', models.CharField(blank=True, max_length=120)),
                ('diplome_principal', models.CharField(blank=True, max_length=200)),
                ('ecole_formation', models.CharField(blank=True, max_length=200)),
                ('annee_diplome', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('secteur', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé'), ('confessionnel', 'Confessionnel')], default='public', max_length=20)),
                ('statut_agent', models.CharField(choices=[('actif', 'En activité'), ('detache', 'Détaché'), ('conge', 'Congé longue durée'), ('retraite', 'Retraité'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('type_contrat', models.CharField(choices=[('permanent', 'Permanent'), ('contractuel', 'Contractuel'), ('prestataire', 'Prestataire'), ('stagiaire', 'Stagiaire')], default='permanent', max_length=20)),
                ('poste_occupe', models.CharField(blank=True, max_length=200)),
                ('date_prise_service', models.DateField(blank=True, null=True)),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('depart_retraite_prevu', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationalite', models.CharField(default='Béninoise', max_length=80)),
                ('actif', models.BooleanField(default=True)),
                ('source_fichier', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='api.campagnecollecte')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='api.structure')),
            ],
            options={
                'verbose_name': 'Agent de santé',
                'verbose_name_plural': 'Agents de santé',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentsante',
            constraint=models.UniqueConstraint(fields=('campagne', 'matricule'), name='unique_agent_campagne_matricule'),
        ),
    ]
