# Generated by Django 4.2.30 on 2026-08-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_actif_to_org_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur ORHS'), ('coordination', 'Coordination ORHS'), ('analyste', 'Analyste / Statisticien'), ('validateur', 'Validateur'), ('collecteur', 'Collecteur'), ('decideur', 'Décideur'), ('partenaire', 'Partenaire accrédité')], max_length=20),
        ),
    ]
