# Generated by Django 4.2.30 on 2026-08-14 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importfichier',
            options={},
        ),
        migrations.RemoveField(
            model_name='importfichier',
            name='campagne',
        ),
        migrations.RemoveField(
            model_name='importfichier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='importfichier',
            name='importe_par',
        ),
        migrations.RemoveField(
            model_name='importfichier',
            name='lignes_erreur',
        ),
        migrations.RemoveField(
            model_name='importfichier',
            name='lignes_ok',
        ),
        migrations.RemoveField(
            model_name='importfichier',
            name='lignes_total',
        ),
        migrations.RemoveField(
            model_name='importfichier',
            name='nom_fichier',
        ),
        migrations.RemoveField(
            model_name='importfichier',
            name='rapport_erreurs',
        ),
        migrations.RemoveField(
            model_name='importfichier',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='importfichier',
            name='structure',
        ),
        migrations.CreateModel(
            name='AgentQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('niveau', models.CharField(blank=True, max_length=120)),
                ('ecole', models.CharField(blank=True, max_length=200)),
                ('date_obtention', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_cours', max_length=20)),
                ('lignes_total', models.PositiveIntegerField(default=0)),
                ('lignes_ok', models.PositiveIntegerField(default=0)),
                ('lignes_erreur', models.PositiveIntegerField(default=0)),
                ('rapport_erreurs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='api.agentsante')),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifications_ajoutees', to=settings.AUTH_USER_MODEL)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='api.campagnecollecte')),
                ('importe_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_fichiers', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='api.structure')),
            ],
            options={
                'verbose_name': 'Import fichier',
                'verbose_name_plural': 'Imports fichiers',
                'ordering': ['-created_at'],
            },
        ),
    ]
