# Generated by Django 4.2.30 on 2026-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_importfichier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsante',
            name='date_suspension',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentsante',
            name='email_pro',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agentsante',
            name='historique_contrats',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='agentsante',
            name='identifiant_rh',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentsante',
            name='matricule_externe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentsante',
            name='statut_administratif',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='agentsante',
            name='telephone_pro',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
