# Generated by Django 4.2.30 on 2026-08-21 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_agentsante_date_suspension_agentsante_email_pro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonné newsletter',
                'verbose_name_plural': 'Abonnés newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionOrdre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entree', models.CharField(choices=[('medecin', 'Médecin'), ('clinique', 'Clinique')], max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('numero_inscription', models.CharField(blank=True, max_length=80)),
                ('ordre', models.CharField(default='Ordre National des Médecins du Bénin', max_length=150)),
                ('specialite', models.CharField(blank=True, max_length=120)),
                ('departement', models.CharField(blank=True, max_length=80)),
                ('commune', models.CharField(blank=True, max_length=80)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('suspendu', 'Suspendu'), ('radie', 'Radié')], default='inscrit', max_length=20)),
                ('inscrit_depuis', models.DateField(blank=True, null=True)),
                ('titre', models.CharField(blank=True, max_length=40)),
                ('nationalite', models.CharField(blank=True, max_length=80)),
                ('universite', models.CharField(blank=True, max_length=200)),
                ('annee_diplome', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mode_exercice', models.CharField(blank=True, max_length=20)),
                ('lieu_exercice', models.CharField(blank=True, max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('directeur', models.CharField(blank=True, max_length=200)),
                ('numero_autorisation', models.CharField(blank=True, max_length=80)),
                ('lits', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publie', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inscription à un ordre',
                'verbose_name_plural': 'Inscriptions aux ordres',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ContenuEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contenu', models.CharField(choices=[('actualite', 'Actualité'), ('evenement', 'Événement'), ('opportunite', 'Opportunité'), ('faq', 'FAQ'), ('texte_legal', 'Texte juridique'), ('formation', 'Formation / institution')], max_length=20)),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('resume', models.TextField(blank=True)),
                ('contenu', models.TextField(blank=True)),
                ('categorie', models.CharField(blank=True, max_length=80)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('publie', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenus_editoriaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenu éditorial',
                'verbose_name_plural': 'Contenus éditoriaux',
                'ordering': ['-date_publication', '-created_at'],
                'indexes': [models.Index(fields=['type_contenu', 'publie'], name='api_contenu_type_co_dc8d73_idx')],
            },
        ),
    ]
