# Generated by Django 4.2.30 on 2026-08-22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0009_contenu_editorial_annuaire_newsletter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agentqualification",
            name="campagne",
        ),
        migrations.RemoveField(
            model_name="agentqualification",
            name="importe_par",
        ),
        migrations.RemoveField(
            model_name="agentqualification",
            name="lignes_erreur",
        ),
        migrations.RemoveField(
            model_name="agentqualification",
            name="lignes_ok",
        ),
        migrations.RemoveField(
            model_name="agentqualification",
            name="lignes_total",
        ),
        migrations.RemoveField(
            model_name="agentqualification",
            name="nom_fichier",
        ),
        migrations.RemoveField(
            model_name="agentqualification",
            name="rapport_erreurs",
        ),
        migrations.RemoveField(
            model_name="agentqualification",
            name="statut",
        ),
        migrations.RemoveField(
            model_name="agentqualification",
            name="structure",
        ),
        migrations.AlterModelOptions(
            name="agentqualification",
            options={
                "ordering": ["-date_obtention", "-created_at"],
                "verbose_name": "Qualification agent",
                "verbose_name_plural": "Qualifications agents",
            },
        ),
        migrations.AddField(
            model_name="importfichier",
            name="campagne",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="imports",
                to="api.campagnecollecte",
            ),
        ),
        migrations.AddField(
            model_name="importfichier",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="importfichier",
            name="importe_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imports_fichiers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="importfichier",
            name="lignes_erreur",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importfichier",
            name="lignes_ok",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importfichier",
            name="lignes_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importfichier",
            name="nom_fichier",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="importfichier",
            name="rapport_erreurs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="importfichier",
            name="statut",
            field=models.CharField(
                choices=[("en_cours", "En cours"), ("termine", "Terminé"), ("erreur", "Erreur")],
                default="en_cours",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="importfichier",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imports",
                to="api.structure",
            ),
        ),
        migrations.AlterModelOptions(
            name="importfichier",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Import fichier",
                "verbose_name_plural": "Imports fichiers",
            },
        ),
        migrations.AlterField(
            model_name="agentsante",
            name="statut_agent",
            field=models.CharField(
                choices=[
                    ("actif", "En activité"),
                    ("detache", "Détaché"),
                    ("conge", "Congé longue durée"),
                    ("retraite", "Retraité"),
                    ("suspendu", "Suspendu"),
                    ("interimaire", "Intérimaire"),
                    ("remplacant", "Remplaçant"),
                ],
                default="actif",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agentsante",
            name="type_contrat",
            field=models.CharField(
                choices=[
                    ("permanent", "Permanent"),
                    ("contractuel", "Contractuel"),
                    ("prestataire", "Prestataire"),
                    ("stagiaire", "Stagiaire"),
                    ("interimaire", "Intérimaire"),
                    ("remplacant", "Remplaçant"),
                ],
                default="permanent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mouvementagent",
            name="type_mouvement",
            field=models.CharField(
                choices=[
                    ("affectation", "Affectation"),
                    ("mutation", "Mutation inter-structures"),
                    ("promotion", "Promotion/Avancement"),
                    ("detachment", "Détachement"),
                    ("mise_disposition", "Mise à disposition"),
                    ("conge_ld", "Congé longue durée"),
                    ("retraite", "Départ à la retraite"),
                    ("demission", "Démission"),
                    ("revocation", "Révocation"),
                    ("deces", "Décès"),
                    ("rentree", "Retour de congé/détachement"),
                    ("interim", "Intérim"),
                    ("remplacement", "Remplacement"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="alerteemail",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente d'envoi"),
                    ("envoye", "Envoyé"),
                    ("erreur", "Erreur d'envoi"),
                    ("ignore", "Ignoré"),
                    ("traite", "Traité"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alerteemail",
            name="action_prise",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="alerteemail",
            name="date_traitement",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alerteemail",
            name="traite_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertes_traitees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RapportGenere",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modele", models.CharField(max_length=50)),
                ("nom_modele", models.CharField(blank=True, max_length=200)),
                ("parametres", models.JSONField(blank=True, default=dict)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapports_generes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport généré",
                "verbose_name_plural": "Rapports générés",
                "ordering": ["-created_at"],
            },
        ),
    ]
