# Generated by Django 4.2.30 on 2026-09-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_newsletter_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenueditorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contenus/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/couvertures/%Y/%m/'),
        ),
    ]
